#define NAMES_PATH "./sources/names.txt"
#define SURNAMES_PATH "./sources/surnames.txt"
#define RACES_PATH "./sources/races.txt"
#define ABILITIES_PATH "./sources/abilities.txt"
#define APPEARANCES_PATH "./sources/appearance.txt"
#define ORIGINS_PATH "./sources/origins.txt"
#define TALENTS_PATH "./sources/talents.txt"
#define BEHAVIOURS_PATH "./sources/behaviour.txt"  